# Tutorial for the PwParser class

The `PwParser` class reads the `data-file-schema.xml` file written by `pw.x` in the `prefix.save` folder and
provides the structural and electronic properties of the system.

__The tutorial parses the results of the Tutorial_QeCalculator notebook, run it first.__

In [1]:
# useful to autoreload the module without restarting the kernel
%load_ext autoreload
%autoreload 2

import datetime
import numpy as np
from mppi import Parsers as P
from mppi.Utilities import LatticeUtils as L
np.set_printoptions(precision=5,suppress=True)

print('Notebook executed on', datetime.datetime.now().strftime('%d/%m/%Y %H:%M'))

Notebook executed on 01/10/2026 11:19


## Parse a scf computation

The class is initialized with the name of the xml file (including its path)

In [2]:
scf = P.PwParser('QeCalculator_tutorial/out_scf/si_scf.save/data-file-schema.xml')

Parse file : QeCalculator_tutorial/out_scf/si_scf.save/data-file-schema.xml


The parser sets several attributes of the object. All the quantities are in Hartree atomic units

In [3]:
print('number of atoms    :',scf.natoms)
print('atomic species     :',scf.atomic_species)
print('positions (a.u.)   :',scf.atomic_positions)
print('electrons          :',scf.num_electrons)
print('bands, kpoints     :',scf.nbands,scf.nkpoints)
print('total energy (Ha)  :',scf.energy)
print('occupations kind   :',scf.occupations_kind)

number of atoms    : 2
atomic species     : {'Si': [28.086, 'Si.pbe-mt_fhi.UPF']}
positions (a.u.)   : [['Si', array([-1.2875,  1.2875,  1.2875])], ['Si', array([ 1.2875, -1.2875, -1.2875])]]
electrons          : 8.0
bands, kpoints     : 4 32
total energy (Ha)  : -7.878907587308356
occupations kind   : fixed


## Lattice properties

The lattice vectors (rows of the array) can be expressed in a.u. or in units of the lattice parameter `alat`.
Silicon has a fcc lattice, so the volume of the cell is $a_{lat}^3/4$ and the reciprocal lattice (in units of
$2\pi/a_{lat}$) is a bcc one

In [4]:
print('alat (a.u.) :',scf.alat)
print('lattice vectors (units of alat) :\n',scf.get_lattice(rescale=True))
print('cell volume :',scf.eval_lattice_volume(),'  alat^3/4 :',scf.alat**3/4)
print('reciprocal lattice vectors (units of 2pi/alat) :\n',scf.get_reciprocal_lattice(rescale=True))
print('number of symmetries :',len(scf.syms))

alat (a.u.) : 10.3
lattice vectors (units of alat) :
 [[-0.5  0.   0.5]
 [ 0.   0.5  0.5]
 [-0.5  0.5  0. ]]
cell volume : 273.1817500000001   alat^3/4 : 273.1817500000001
reciprocal lattice vectors (units of 2pi/alat) :
 [[-1. -1.  1.]
 [ 1.  1.  1.]
 [-1.  1. -1.]]
number of symmetries : 48


The functions of the `LatticeUtils` module convert the cartesian coordinates of the atomic positions and of the
k points into crystal ones (in the basis of the direct and reciprocal lattice vectors, respectively), and back

In [5]:
lattice = scf.get_lattice(rescale=True)
rec_lattice = scf.get_reciprocal_lattice(rescale=True)

atom = scf.atomic_positions[1][1]/scf.alat # cartesian coordinates in units of alat
print('second atom in crystal coordinates :',L.convert_to_crystal(lattice,atom))

k_crystal = np.array([L.convert_to_crystal(rec_lattice,k) for k in scf.kpoints])
print('first kpoints in crystal coordinates :\n',k_crystal[:4])
k_cartesian = np.array([L.convert_to_cartesian(rec_lattice,k) for k in k_crystal])
print('conversion back to cartesian coordinates is correct :',np.allclose(k_cartesian,scf.kpoints))

second atom in crystal coordinates : [-0.125 -0.125 -0.125]
first kpoints in crystal coordinates :
 [[ 0.       0.       0.     ]
 [-0.      -0.       0.16667]
 [-0.      -0.       0.33333]
 [ 0.       0.      -0.5    ]]
conversion back to cartesian coordinates is correct : True


## Kohn-Sham energies

The `kpoints` (cartesian coordinates in units of $2\pi/a_{lat}$), their `weights` and the Kohn-Sham energies
`evals` (in Hartree) are stored as arrays. The scf computation contains only the 4 occupied bands of silicon

In [6]:
for k,w,e in zip(scf.kpoints[:3],scf.weights[:3],scf.evals[:3]):
    print('k =',k,' weight =',w,' evals =',e)

k = [0. 0. 0.]  weight = [0.00926]  evals = [-0.21209  0.22478  0.22478  0.22478]
k = [-0.16667  0.16667 -0.16667]  weight = [0.05556]  evals = [-0.19892  0.13762  0.20841  0.20841]
k = [-0.33333  0.33333 -0.33333]  weight = [0.05556]  evals = [-0.16193  0.03001  0.18832  0.18832]


## Parse a nscf computation: gap, scissor and transitions

The nscf computation includes 8 bands, so the empty states are present and the gap can be computed

In [7]:
nscf = P.PwParser('QeCalculator_tutorial/out_nscf/si_scf.save/data-file-schema.xml')
print('occupations at Gamma :',nscf.occupations[0])
gap = nscf.get_gap()

Parse file : QeCalculator_tutorial/out_nscf/si_scf.save/data-file-schema.xml
occupations at Gamma : [1. 1. 1. 1. 0. 0. 0. 0.]
Indirect gap system
Gap : 0.7407917316791695 eV
Direct gap : 2.565295281247253 eV


The `get_evals` method returns the energies in eV, using the top of the valence band as reference. The energies of
the empty bands can be shifted by setting the value of the gap (`set_gap` or `set_direct_gap`) or with an explicit
scissor (`set_scissor`). The occupations of the states are not updated

In [8]:
print('bands at Gamma (eV)                  :',nscf.get_evals(verbose=False)[0])
print('bands at Gamma, direct gap of 3 eV   :',nscf.get_evals(set_direct_gap=3.,verbose=False)[0])
print('bands at Gamma, scissor of 1 eV      :',nscf.get_evals(set_scissor=1.,verbose=False)[0])

bands at Gamma (eV)                  : [-11.88784  -0.00003  -0.        0.        2.5653    2.56533   2.56533
   3.17618]
bands at Gamma, direct gap of 3 eV   : [-11.88784  -0.00003  -0.        0.        3.        3.00003   3.00003
   3.61089]
bands at Gamma, scissor of 1 eV      : [-11.88784  -0.00003  -0.        0.        3.5653    3.56533   3.56533
   4.17618]


The `get_transitions` method computes, for each k point, the energies (in eV) of the vertical transitions from the
`initial` to the `final` bands (by default from the occupied to the empty ones)

In [9]:
transitions = nscf.get_transitions(set_direct_gap=3.)
print('shape of the array (kpoints, transitions) :',transitions.shape)
print('lowest transition energy at Gamma (eV)    :',transitions[0].min())

shape of the array (kpoints, transitions) : (32, 16)
lowest transition energy at Gamma (eV)    : 3.0
